package com.revature.exceptions;

public class AlreadyFollowingException extends RuntimeException {

}
